name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: "true"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - run: cargo test --locked --workspace

  minimal-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@nightly
    - run: cargo update -Z direct-minimal-versions
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test --locked --workspace

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri
    - run: cargo miri test --locked --workspace

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: cargo clippy --locked --workspace -- --deny warnings

  msrv:
    needs: [test, minimal-versions, miri, fmt, clippy, no-default-features, doc]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: extract_msrv
      shell: python
      run: |
        from pathlib import Path
        manifest_path = Path("Cargo.toml")
        manifest = manifest_path.read_text()
        data = manifest.replace("resolver = \"3\"", "resolver = \"2\"")
        manifest_path.write_text(data)

        import tomllib
        data = tomllib.loads(manifest)
        msrv = data["package"]["rust-version"]

        import os
        print(f"msrv={msrv}", file=open(os.environ["GITHUB_OUTPUT"], "a"))
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.extract_msrv.outputs.msrv }}
    - uses: Swatinem/rust-cache@v2
    - run: |
        rm Cargo.lock
    - run: cargo build --workspace --lib

  no-default-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: cargo build --locked --workspace --no-default-features

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: cargo doc --locked --workspace --features docs
